Git: pre-push hook cleanup

diff --git a/.config/git/hooks/pre-push b/.config/git/hooks/pre-push
--- a/.config/git/hooks/pre-push
+++ b/.config/git/hooks/pre-push
@@ -89,7 +89,7 @@ while read -r _ local_sha remote_ref _; do
 		fi
 
 		if [ $return_status ]; then
-			>&2 echo -e "$red$0: $yellow$test ${red}failed with exit code $yellow$return_status$red$clear\a"
+			>&2 echo -e "$red$0: $yellow$test ${red}failed with exit code $yellow$return_status$clear\a"
 			exit $return_status
 		fi
 	fi
